[theme]
primaryColor = "#2fb586"
backgroundColor = "#0b120f"
secondaryBackgroundColor = "#16211b"
textColor = "#eaf2ed"
font = "sans serif"

[server]
maxUploadSize = 10
enableStaticServing = true

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
